// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProFriendsApi.Data;

#nullable disable

namespace ProFriendsAPI.Data.Migrations
{
    [DbContext(typeof(ProfriendsAPIDbContext))]
    [Migration("20240920153220_createdatabase")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProFriendsApi.Models.ProFriendsAPI", b =>
                {
                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("EquityTerm")
                        .HasColumnType("int");

                    b.Property<double>("Insurance")
                        .HasColumnType("float");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<int>("LoanTerm")
                        .HasColumnType("int");

                    b.Property<double>("ProcessingFee")
                        .HasColumnType("float");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<double>("ReservationFee")
                        .HasColumnType("float");

                    b.HasKey("SellingPrice");

                    b.ToTable("ProFriendsAPI");
                });
#pragma warning restore 612, 618
        }
    }
}
